name: Test

on:
  push:
    branches:
      - dev
      - release/*
  pull_request:
    branches:
      - dev
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Generate version
        run: |
          python tools/releasing/release.py
      - name: Install packages
        run: |
          pip install -r dependencies/pip/requirements.txt
          python setup.py check -m -s
      - name: Run tests
        run: |
          tools/test.sh
